# Generated by Django 6.0.7 on 2026-07-12 17:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_ciclo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AderenciaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual de aderência 0–100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='percentual')),
                ('componentes', models.JSONField(blank=True, default=dict, help_text='Breakdown do cálculo de aderência.', verbose_name='componentes')),
                ('calculado_em', models.DateTimeField(verbose_name='calculado em')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aderencia_snapshots', to='cycles.ciclo', verbose_name='ciclo')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aderencia_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='líder')),
            ],
            options={
                'verbose_name': 'snapshot de aderência',
                'verbose_name_plural': 'snapshots de aderência',
                'ordering': ['-calculado_em', 'lider'],
                'constraints': [models.UniqueConstraint(fields=('lider', 'ciclo'), name='unique_aderencia_lider_ciclo'), models.CheckConstraint(condition=models.Q(('percentual__gte', Decimal('0')), ('percentual__lte', Decimal('100'))), name='aderencia_percentual_0_100')],
            },
        ),
    ]
