# Generated by Django 6.0.7 on 2026-07-11 21:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_area_cargo_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('valor_minimo', models.IntegerField(verbose_name='valor mínimo')),
                ('valor_maximo', models.IntegerField(verbose_name='valor máximo')),
                ('rotulos_por_nivel', models.JSONField(blank=True, default=dict, help_text='Mapa nível → rótulo (ex.: {"1": "Iniciante", "5": "Expert"}).', verbose_name='rótulos por nível')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('comportamental', 'Comportamental'), ('lideranca', 'Liderança')], max_length=20, verbose_name='tipo')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='competencies.escala', verbose_name='escala')),
            ],
            options={
                'verbose_name': 'competência',
                'verbose_name_plural': 'competências',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CargoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nivel_esperado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='nível esperado')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='peso')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_competencias', to='organization.cargo', verbose_name='cargo')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_competencias', to='competencies.competencia', verbose_name='competência')),
            ],
            options={
                'verbose_name': 'competência do cargo',
                'verbose_name_plural': 'competências do cargo',
                'ordering': ['cargo', 'competencia'],
                'constraints': [models.UniqueConstraint(fields=('cargo', 'competencia'), name='unique_cargo_competencia')],
            },
        ),
    ]
