# Generated by Django 6.0.7 on 2026-07-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(help_text='Informativo; o encerramento é manual.', verbose_name='data de fim')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado')], default='encerrado', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'ciclo',
                'verbose_name_plural': 'ciclos',
                'ordering': ['-data_inicio', 'nome'],
            },
        ),
    ]
