# Generated by Django 6.0.7 on 2026-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='solides_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID Sólides'),
        ),
    ]
