# Generated by Django 6.0.7 on 2026-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_add_solides_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='admitidos_ate',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='admitidos até',
            ),
        ),
    ]
