# Generated by Django 6.0.7 on 2026-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_ciclo_admitidos_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='marco_competencia',
            field=models.DateField(blank=True, help_text='Para ciclos automáticos: sempre o dia 1 do mês de marco (YYYY-MM-01). Nulo em ciclos manuais.', null=True, verbose_name='marco de competência'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20, verbose_name='origem'),
        ),
        migrations.AddConstraint(
            model_name='ciclo',
            constraint=models.UniqueConstraint(condition=models.Q(('marco_competencia__isnull', False), ('origem', 'automatico')), fields=('marco_competencia',), name='unique_ciclo_automatico_marco_competencia'),
        ),
    ]
