# Generated by Django 6.0.7 on 2026-09-10 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_ciclo_origem_marco_competencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCycleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('executado_em', models.DateTimeField(verbose_name='executado em')),
                ('data_referencia', models.DateField(verbose_name='data de referência')),
                ('era_primeiro_dia_util', models.BooleanField(default=False, verbose_name='era primeiro dia útil')),
                ('marco_competencia', models.DateField(blank=True, help_text='Preenchido se a rotina tentou ou abriu coorte no mês.', null=True, verbose_name='marco de competência')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('noop', 'No-op'), ('parcial', 'Parcial'), ('falha', 'Falha')], default='noop', max_length=20, verbose_name='status')),
                ('matriculados', models.PositiveIntegerField(default=0, verbose_name='matriculados')),
                ('alertas_ciclo_aberto', models.PositiveIntegerField(default=0, verbose_name='alertas ciclo aberto')),
                ('excluidos_sem_admissao', models.PositiveIntegerField(default=0, verbose_name='excluídos sem admissão')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='mensagem')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_cycle_runs', to='cycles.ciclo', verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'execução automática de ciclo',
                'verbose_name_plural': 'execuções automáticas de ciclo',
                'ordering': ['-executado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AutoCycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matricula', 'Matrícula'), ('alerta_ciclo_aberto', 'Alerta ciclo aberto'), ('pendencia_sem_admissao', 'Pendência sem admissão'), ('falha', 'Falha'), ('noop_dia', 'No-op do dia'), ('coorte_criada', 'Coorte criada'), ('coorte_reusada', 'Coorte reusada')], max_length=32, verbose_name='tipo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_cycle_events', to='cycles.ciclo', verbose_name='ciclo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_cycle_events', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cycles.autocyclerun', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'evento automático de ciclo',
                'verbose_name_plural': 'eventos automáticos de ciclo',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['run', 'tipo'], name='cycles_auto_run_id_f81ace_idx'), models.Index(fields=['tipo'], name='cycles_auto_tipo_1ea2f4_idx'), models.Index(fields=['criado_em'], name='cycles_auto_criado__1cb4ad_idx')],
            },
        ),
    ]
