# Generated by Django 6.0.7 on 2026-07-12 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_ciclo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoTalento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('desempenho', models.PositiveSmallIntegerField(help_text='Nível 1–3 derivado da nota_final_lider normalizada.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='desempenho')),
                ('potencial', models.PositiveSmallIntegerField(help_text='Nível 1–3 definido manualmente pelo admin.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='potencial')),
                ('quadrante', models.CharField(choices=[('baixo_baixo', 'Baixo / Baixo'), ('baixo_medio', 'Baixo / Médio'), ('baixo_alto', 'Baixo / Alto'), ('medio_baixo', 'Médio / Baixo'), ('medio_medio', 'Médio / Médio'), ('medio_alto', 'Médio / Alto'), ('alto_baixo', 'Alto / Baixo'), ('alto_medio', 'Alto / Médio'), ('alto_alto', 'Alto / Alto')], max_length=20, verbose_name='quadrante')),
                ('visivel_ao_colaborador', models.BooleanField(default=False, verbose_name='visível ao colaborador')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classificacoes_talento', to='cycles.ciclo', verbose_name='ciclo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classificacoes_talento', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'classificação de talento',
                'verbose_name_plural': 'classificações de talento',
                'ordering': ['ciclo', 'usuario'],
                'constraints': [models.CheckConstraint(condition=models.Q(('desempenho__gte', 1), ('desempenho__lte', 3)), name='talent_desempenho_1_3'), models.CheckConstraint(condition=models.Q(('potencial__gte', 1), ('potencial__lte', 3)), name='talent_potencial_1_3')],
                'unique_together': {('usuario', 'ciclo')},
            },
        ),
    ]
