# Generated by Django 6.0.7 on 2026-07-12 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('access_denied', 'Acesso negado')], max_length=32, verbose_name='ação')),
                ('entity_type', models.CharField(max_length=100, verbose_name='tipo da entidade')),
                ('entity_id', models.PositiveIntegerField(verbose_name='id da entidade')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='valor novo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario'], name='audit_audit_usuario_752999_idx'), models.Index(fields=['acao'], name='audit_audit_acao_e17a49_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
