# Generated by Django 6.0.7 on 2026-07-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('concluido', 'Concluído'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdis', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'PDI',
                'verbose_name_plural': 'PDIs',
                'ordering': ['usuario', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcaoPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('prazo', models.DateField(verbose_name='prazo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada')], default='pendente', max_length=20, verbose_name='status')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_pdi', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='pdi.pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'ação de PDI',
                'verbose_name_plural': 'ações de PDI',
                'ordering': ['prazo', 'id'],
            },
        ),
    ]
