# Generated by Django 6.0.7 on 2026-07-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_ciclo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('etapa', models.CharField(choices=[('input_metas', 'Input de metas'), ('aprovacao_metas', 'Aprovação de metas'), ('resultados', 'Resultados'), ('aprovacao_resultados', 'Aprovação de resultados'), ('avaliacao', 'Avaliação'), ('feedback', 'Feedback')], default='input_metas', max_length=30, verbose_name='etapa')),
                ('nota_final_lider', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='nota final do líder')),
                ('nota_final_autoavaliacao', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='nota final da autoavaliação')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='cycles.ciclo', verbose_name='ciclo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['ciclo', 'usuario'],
                'unique_together': {('ciclo', 'usuario')},
            },
        ),
    ]
