# Generated by Django 6.0.7 on 2026-07-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_escala_competencia_cargocompetencia'),
        ('reviews', '0001_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nota_autoavaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='nota da autoavaliação')),
                ('nota_lider', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='nota do líder')),
                ('peso_utilizado', models.DecimalField(decimal_places=2, help_text='Snapshot write-once do peso do cargo no momento da avaliação.', max_digits=8, verbose_name='peso utilizado')),
                ('nivel_esperado_utilizado', models.DecimalField(decimal_places=2, help_text='Snapshot write-once do nível esperado no momento da avaliação.', max_digits=8, verbose_name='nível esperado utilizado')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_competencia', to='reviews.avaliacao', verbose_name='avaliação')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_competencia', to='competencies.competencia', verbose_name='competência')),
            ],
            options={
                'verbose_name': 'avaliação de competência',
                'verbose_name_plural': 'avaliações de competência',
                'ordering': ['avaliacao', 'competencia'],
                'constraints': [models.UniqueConstraint(fields=('avaliacao', 'competencia'), name='unique_avaliacao_competencia')],
            },
        ),
    ]
