# Generated by Django 6.0.7 on 2026-07-12 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_avaliacaocompetencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('colaborador', 'Colaborador'), ('lider', 'Líder')], max_length=20, verbose_name='tipo')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('ciente_em', models.DateTimeField(blank=True, null=True, verbose_name='ciente em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_autorados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='reviews.avaliacao', verbose_name='avaliação')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
