# Generated by Django 6.0.7 on 2026-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='concluida',
            field=models.BooleanField(default=False, help_text='True quando feedback do líder tem ciente_em; congelado no encerramento do ciclo para o indicador de conclusão.', verbose_name='concluída'),
        ),
    ]
