# Generated by Django 6.0.7 on 2026-08-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_etapa_input_metas_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='solides_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID Sólides'),
        ),
    ]
