# Generated by Django 6.0.7 on 2026-09-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_avaliacao_autoavaliacao_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackContinuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('ciente_em', models.DateTimeField(blank=True, null=True, verbose_name='ciente em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_continuos_autorados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_continuos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'feedback contínuo',
                'verbose_name_plural': 'feedbacks contínuos',
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['destinatario', '-created_at'], name='reviews_fee_destina_6625e1_idx'), models.Index(fields=['autor', '-created_at'], name='reviews_fee_autor_i_b8418e_idx')],
            },
        ),
    ]
