# Generated by Django 6.0.7 on 2026-07-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_estrategicos', to='cycles.ciclo', verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'objetivo estratégico',
                'verbose_name_plural': 'objetivos estratégicos',
                'ordering': ['ciclo', 'id'],
            },
        ),
    ]
