# Generated by Django 6.0.7 on 2026-07-12 01:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_objetivo_estrategico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('progresso', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual 0–100; editável apenas na etapa resultados.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='progresso')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], default='pendente', max_length=20, verbose_name='status')),
                ('status_resultado', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='status do resultado')),
                ('objetivo_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='goals.objetivoestrategico', verbose_name='objetivo estratégico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['objetivo_estrategico', 'usuario', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('progresso__isnull', True), models.Q(('progresso__gte', Decimal('0')), ('progresso__lte', Decimal('100'))), _connector='OR'), name='meta_progresso_entre_0_e_100')],
            },
        ),
    ]
