# Generated by Django 6.0.7 on 2026-07-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lembrete_etapa', 'Lembrete de etapa'), ('lembrete_pdi', 'Lembrete de ação PDI')], max_length=32, verbose_name='tipo')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha')], max_length=16, verbose_name='status')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacao_logs', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'log de notificação',
                'verbose_name_plural': 'logs de notificação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario'], name='notificatio_destina_239a33_idx'), models.Index(fields=['tipo'], name='notificatio_tipo_6c514b_idx'), models.Index(fields=['status'], name='notificatio_status_b0e97f_idx'), models.Index(fields=['created_at'], name='notificatio_created_1b71ad_idx')],
            },
        ),
    ]
