# Generated by Django 6.0.7 on 2026-09-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificacaolog_referencia_janela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaolog',
            name='tipo',
            field=models.CharField(choices=[('lembrete_etapa', 'Lembrete de etapa'), ('lembrete_pdi', 'Lembrete de ação PDI'), ('feedback_continuo', 'Feedback contínuo')], max_length=32, verbose_name='tipo'),
        ),
    ]
