# Generated by Django 6.0.7 on 2026-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_feedback_continuo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaolog',
            name='tipo',
            field=models.CharField(choices=[('lembrete_etapa', 'Lembrete de etapa'), ('lembrete_pdi', 'Lembrete de ação PDI'), ('feedback_continuo', 'Feedback contínuo'), ('atraso_pdi', 'Atraso de ação PDI'), ('digest_pdi_atrasos', 'Digest de PDIs atrasados')], max_length=32, verbose_name='tipo'),
        ),
    ]
