# Generated by Django 6.0.7 on 2026-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificacaolog_atraso_digest_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaolog',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('lembrete_etapa', 'Lembrete de etapa'),
                    ('lembrete_pdi', 'Lembrete de ação PDI'),
                    ('feedback_continuo', 'Feedback contínuo'),
                    ('atraso_pdi', 'Atraso de ação PDI'),
                    ('digest_pdi_atrasos', 'Digest de PDIs atrasados'),
                    ('alerta_ciclo_ainda_aberto', 'Alerta ciclo ainda aberto'),
                ],
                max_length=32,
                verbose_name='tipo',
            ),
        ),
    ]
